const productList = [
  {
    "title": "Wireless Bluetooth Headphones",
    "special_price": 1999,
    "price": 2499,
    "image": "https://example.com/images/headphones.jpg",
    "category": "Electronics",
    "subCategory": "Audio",
    "remarks": "Best Seller",
    "brand": "SoundMax",
    "shop": "tech-store-001",
    "shop_name": "Tech Store",
    "product_code": "SM-HB1001",
    "stock": 50,
    "rating": 4.5
  },
  {
    "title": "Men's Casual Denim Jacket",
    "special_price": 1499,
    "price": 1999,
    "image": "https://example.com/images/denim-jacket.jpg",
    "category": "Fashion",
    "subCategory": "Men",
    "remarks": "Trending",
    "brand": "DenimCo",
    "shop": "fashion-hub-002",
    "shop_name": "Fashion Hub",
    "product_code": "DC-MJ202",
    "stock": 75,
    "rating": 4.2
  },
  {
    "title": "Smart LED TV 43 inch",
    "special_price": 28999,
    "price": 34999,
    "image": "https://example.com/images/led-tv.jpg",
    "category": "Electronics",
    "subCategory": "TV",
    "remarks": "Limited Offer",
    "brand": "ViewTech",
    "shop": "home-elec-003",
    "shop_name": "Home Electronics",
    "product_code": "VT-TV43X",
    "stock": 20,
    "rating": 4.6
  },
  {
    "title": "Women's Silk Scarf",
    "special_price": 599,
    "price": 799,
    "image": "https://example.com/images/silk-scarf.jpg",
    "category": "Fashion",
    "subCategory": "Women",
    "remarks": "New Arrival",
    "brand": "SilkyWear",
    "shop": "style-corner-004",
    "shop_name": "Style Corner",
    "product_code": "SW-WSF01",
    "stock": 100,
    "rating": 4.3
  },
  {
    "title": "Gaming Mouse RGB",
    "special_price": 1099,
    "price": 1399,
    "image": "https://example.com/images/gaming-mouse.jpg",
    "category": "Electronics",
    "subCategory": "Accessories",
    "remarks": "High Demand",
    "brand": "GamerPro",
    "shop": "tech-store-001",
    "shop_name": "Tech Store",
    "product_code": "GP-MX88",
    "stock": 80,
    "rating": 4.7
  },
  {
    "title": "Yoga Mat Eco-Friendly",
    "special_price": 799,
    "price": 999,
    "image": "https://example.com/images/yoga-mat.jpg",
    "category": "Health",
    "subCategory": "Fitness",
    "remarks": "Top Rated",
    "brand": "FlexFit",
    "shop": "active-life-005",
    "shop_name": "Active Life",
    "product_code": "FF-YM909",
    "stock": 60,
    "rating": 4.8
  },
  {
    "title": "Stainless Steel Water Bottle",
    "special_price": 449,
    "price": 599,
    "image": "https://example.com/images/water-bottle.jpg",
    "category": "Home & Kitchen",
    "subCategory": "Kitchen",
    "remarks": "Best Value",
    "brand": "CoolSip",
    "shop": "kitchen-mart-006",
    "shop_name": "Kitchen Mart",
    "product_code": "CS-WB300",
    "stock": 120,
    "rating": 4.1
  },
  {
    "title": "Leather Office Bag",
    "special_price": 2299,
    "price": 2799,
    "image": "https://example.com/images/leather-bag.jpg",
    "category": "Fashion",
    "subCategory": "Men",
    "remarks": "Premium",
    "brand": "UrbanStyle",
    "shop": "fashion-hub-002",
    "shop_name": "Fashion Hub",
    "product_code": "US-LB007",
    "stock": 45,
    "rating": 4.4
  },
  {
    "title": "Noise Cancelling Earbuds",
    "special_price": 2499,
    "price": 2999,
    "image": "https://example.com/images/earbuds.jpg",
    "category": "Electronics",
    "subCategory": "Audio",
    "remarks": "Editor's Choice",
    "brand": "AudioZen",
    "shop": "tech-store-001",
    "shop_name": "Tech Store",
    "product_code": "AZ-NC900",
    "stock": 35,
    "rating": 4.6
  },
  {
    "title": "Non-Stick Frying Pan 24cm",
    "special_price": 699,
    "price": 899,
    "image": "https://example.com/images/frying-pan.jpg",
    "category": "Home & Kitchen",
    "subCategory": "Cookware",
    "remarks": "Durable",
    "brand": "CookRight",
    "shop": "kitchen-mart-006",
    "shop_name": "Kitchen Mart",
    "product_code": "CR-FP24",
    "stock": 70,
    "rating": 4.0
  },
  {
    "title": "Stainless Steel Knife Set",
    "special_price": 1299,
    "price": 1699,
    "image": "https://example.com/images/knife-set.jpg",
    "category": "Home & Kitchen",
    "subCategory": "Cutlery",
    "remarks": "Bestseller",
    "brand": "SharpEdge",
    "shop": "kitchen-mart-006",
    "shop_name": "Kitchen Mart",
    "product_code": "SE-KN5",
    "stock": 90,
    "rating": 4.5
  },
  {
    "title": "Wireless Keyboard and Mouse Combo",
    "special_price": 1799,
    "price": 2299,
    "image": "https://example.com/images/keyboard-mouse.jpg",
    "category": "Electronics",
    "subCategory": "Accessories",
    "remarks": "Combo Offer",
    "brand": "TypeGo",
    "shop": "tech-store-001",
    "shop_name": "Tech Store",
    "product_code": "TG-KMC12",
    "stock": 55,
    "rating": 4.2
  },
  {
    "title": "Baby Cotton Blanket",
    "special_price": 899,
    "price": 1199,
    "image": "https://example.com/images/baby-blanket.jpg",
    "category": "Kids",
    "subCategory": "Baby",
    "remarks": "Soft & Cozy",
    "brand": "BabySnug",
    "shop": "kids-world-007",
    "shop_name": "Kids World",
    "product_code": "BS-BLKT",
    "stock": 85,
    "rating": 4.7
  },
  {
    "title": "Digital Drawing Tablet",
    "special_price": 3699,
    "price": 4499,
    "image": "https://example.com/images/drawing-tablet.jpg",
    "category": "Electronics",
    "subCategory": "Computer",
    "remarks": "For Creators",
    "brand": "DrawLine",
    "shop": "tech-store-001",
    "shop_name": "Tech Store",
    "product_code": "DL-TB10",
    "stock": 40,
    "rating": 4.8
  },
  {
    "title": "Men's Running Shoes",
    "special_price": 1699,
    "price": 2199,
    "image": "https://example.com/images/running-shoes.jpg",
    "category": "Fashion",
    "subCategory": "Footwear",
    "remarks": "Comfort Fit",
    "brand": "SpeedoFlex",
    "shop": "sports-gear-008",
    "shop_name": "Sports Gear",
    "product_code": "SF-RS112",
    "stock": 65,
    "rating": 4.4
  },
  {
    "title": "Rechargeable Hair Trimmer",
    "special_price": 999,
    "price": 1299,
    "image": "https://example.com/images/hair-trimmer.jpg",
    "category": "Beauty",
    "subCategory": "Men",
    "remarks": "Best Grooming",
    "brand": "TrimPro",
    "shop": "groom-zone-009",
    "shop_name": "Groom Zone",
    "product_code": "TP-HT700",
    "stock": 58,
    "rating": 4.6
  },
  {
    "title": "Girls Floral Print Dress",
    "special_price": 1199,
    "price": 1499,
    "image": "https://example.com/images/floral-dress.jpg",
    "category": "Fashion",
    "subCategory": "Girls",
    "remarks": "Adorable",
    "brand": "TinyTrend",
    "shop": "kids-world-007",
    "shop_name": "Kids World",
    "product_code": "TT-GFD01",
    "stock": 72,
    "rating": 4.5
  },
  {
    "title": "Laptop Cooling Pad",
    "special_price": 799,
    "price": 1099,
    "image": "https://example.com/images/cooling-pad.jpg",
    "category": "Electronics",
    "subCategory": "Accessories",
    "remarks": "Quiet Fan",
    "brand": "CoolMate",
    "shop": "tech-store-001",
    "shop_name": "Tech Store",
    "product_code": "CM-LCP88",
    "stock": 67,
    "rating": 4.3
  },
  {
    "title": "3-Layer Steel Tiffin Box",
    "special_price": 649,
    "price": 849,
    "image": "https://example.com/images/tiffin-box.jpg",
    "category": "Home & Kitchen",
    "subCategory": "Lunchware",
    "remarks": "Leak Proof",
    "brand": "TiffinKing",
    "shop": "kitchen-mart-006",
    "shop_name": "Kitchen Mart",
    "product_code": "TK-TF3",
    "stock": 95,
    "rating": 4.4
  },
  {
    "title": "Compact Travel Umbrella",
    "special_price": 499,
    "price": 649,
    "image": "https://example.com/images/travel-umbrella.jpg",
    "category": "Travel",
    "subCategory": "Accessories",
    "remarks": "Windproof",
    "brand": "RainGuard",
    "shop": "outdoor-shop-010",
    "shop_name": "Outdoor Shop",
    "product_code": "RG-UMB06",
    "stock": 88,
    "rating": 4.2
  }
]
module.exports = productList;